# Vectors and Matrices
Time to work! Do it with numpy first and then if you have time, manually by hand :)

## Vectors

Lists can be used to represent mathematical vectors. In this exercise and several that follow you will write functions to perform standard operations on vectors. Create a file named vectors.py or use the Jupyter notebook provided

Write a function add_vectors(u, v) that takes two lists of numbers of the same length, and returns a new list containing the sums of the corresponding elements of each.

**Note that the text in """ """ is provided for you to accurately verify that your function works :)**

In [172]:
import numpy as np

#1st
def add_vectors(u, v):
  add_vectors = u + v
  return add_vectors
result = add_vectors(np.array([1,0]), np.array([1,1]))
result

#2nd
def add_vectors2(u, v):
  add_vectors2 = u + v
  return add_vectors2
result2 = add_vectors2(np.array([1,2]), np.array([1,4]))
result2


#3rd (3D)
def add_vectors3(u, v):
  add_vectors3 = u + v
  return add_vectors3
result3 = add_vectors3(np.array([1,2,1]), np.array([1,4,3]))
result3


#4th (4D)
def add_vectors4(u, v):
  add_vectors4 = u + v
  return add_vectors4
result4 = add_vectors4(np.array([11,0,-4,5]), np.array([2,-4,17,0]))
result4

#5th (3D)
def add_vectors5(a, b):
  add_vectors5 = a + b
  return add_vectors5
a = np.array([1,2,3])
b = np.array([1,1,1])
result5 = add_vectors5(a,b)

#result4
#a
b




array([1, 1, 1])

Write a function scalar_mult(s, v) that takes a number, s, and a list, v and returns the [scalar multiple](https://en.wikipedia.org/wiki/Scalar_multiplication) of v by s.

In [142]:
#1st
def scalar_mult(s, v):
  mult_vectors = s * v
  return mult_vectors
result = scalar_mult(5, np.array([1,2]))
result

#2nd (3D)
def scalar_mult2(s, v):
  mult_vectors = s * v
  return mult_vectors
result2 = scalar_mult2(3, np.array([1,0,-1]))
result2

#3rd (5D)
def scalar_mult3(s, v):
  mult_vectors = s * v
  return mult_vectors
result3 = scalar_mult3(7, np.array([3,0,5,11,2]))
result3

#4th (3D)
def scalar_mult4(s, v):
  mult_vectors = s * v
  return mult_vectors
a = np.array([1,2,3])
result4 = scalar_mult4(4,a)
result4
a



array([1, 2, 3])

Write a function dot_product(u, v) that takes two lists of numbers of the same length, and returns the sum of the products of the corresponding elements of each (the [dot_product](https://en.wikipedia.org/wiki/Dot_product).

In [143]:
#1st
def dot_product(u, v):
  mult_product = np.dot(u,v)
  return mult_product
result = dot_product(np.array([1,1]),np.array([1,1]))
result

#2nd
def dot_product2(u, v):
  mult_product = np.dot(u,v)
  return mult_product
result2 = dot_product(np.array([1,2]),np.array([1,4]))
result2

#3rd
def dot_product3(u, v):
  mult_product = np.dot(u,v)
  return mult_product
result3 = dot_product(np.array([1,2,1]),np.array([1,4,3]))
result3

#4th
def dot_product4(u, v):
  mult_product = np.dot(u,v)
  return mult_product
result4 = dot_product(np.array([2,0,-1,1]),np.array([1,5,2,0]))
result4


0

## Matrices

Create a new module named matrices.py or *use the Jupyter notebook provided* and add the following function, which returns a copy of nested lists of numbers such that the lists are not aliases:

In [505]:
#1st 
def copy_matrix(matrix):
  copymatrices = np.array(matrix)
  return copymatrices
result = copy_matrix([[1,2],[3,4]])
result

#2nd 
def copy_matrix2(matrix):
  copymatrices = np.array(matrix)
  return copymatrices
result2 = copy_matrix2([[1,2,3],[4,5,6]])
result2

#3rd
def copy_matrix3(matrix):
  copymatrices = np.array(matrix)
  return copymatrices
result3 = copy_matrix3([[1,2],[3,4],[5,6],[7,8]])
result3

#4th
def copy_matrix4(m):
  copymatrices = np.array(m)
  return copymatrices
m = [[1, 0, 0], [0, 2, 0], [0, 0, 3]]
result4 = copy_matrix(m)
copyofm = copy_matrix(m)
result4

#5th

for row_num, row in enumerate(copyofm):
    for col_num, col_val in enumerate(row):
        copyofm[row_num][col_num] = 42
copyofm

m




[[1, 0, 0], [0, 2, 0], [0, 0, 3]]

In [161]:
#1st 
def add_row(m):
    addition_row = np.append(m,[row],axis= 0)
    return addition_row
row = np.array([0,0])
result = add_row([[0,0],[0,0]])
#matrix
result

def add_rown(n):
    addition_rown = np.append(n,[row],axis= 0)
    return addition_rown
n = [[3, 2, 5], [1, 4, 7]]
row = np.array([0,0,0])
result = add_rown(n)
#result
n


[[3, 2, 5], [1, 4, 7]]

In [170]:
def add_column(m):
  addition_column = np.append(m,column,axis= 1)
  return addition_column
column = [[0],
         [0]]
result = add_column([[0,0],[0,0]])
#matrix
result

def add_columnn(n):
    addition_columnn = np.append(n,column,axis= 1)
    return addition_columnn
n = [[3,2],[5,1],[4,7]]
column = [[0],
          [0],
          [0]]
result = add_columnn(n)
result
n
"""
m = [[0, 0], [0, 0]]
add_column(m)
[[0, 0, 0], [0, 0, 0]]
n = [[3, 2], [5, 1], [4, 7]]
add_column(n)
[[3, 2, 0], [5, 1, 0], [4, 7, 0]]
n
[[3, 2], [5, 1], [4, 7]]
"""


[[3, 2], [5, 1], [4, 7]]

Write a function add_matrices(m1, m2) that adds m1 and m2 and returns a new matrix containing their sum. You can assume that m1 and m2 are the same size. You add two matrices by adding their corresponding values.

In [497]:
def add_matrices(a, b):
  add_matrix = a + b
  return add_matrix
a = np.matrix([[1, 2], [3, 4]])
b = np.matrix([[2, 2], [2, 2]])
result = add_matrices(a,b)
result
    
def add_matrices2(c, d):
  add_matrix2 = c + d
  return add_matrix2
c = np.array([[8, 2], [3, 4], [5, 7]])
d = np.array([[3, 2], [9, 2], [10, 12]])
result = add_matrices2(c, d)
result
c
d
"""
a = [[1, 2], [3, 4]]
b = [[2, 2], [2, 2]]
add_matrices(a, b)
[[3, 4], [5, 6]]
c = [[8, 2], [3, 4], [5, 7]]
d = [[3, 2], [9, 2], [10, 12]]
add_matrices(c, d)
[[11, 4], [12, 6], [15, 19]]
c
[[8, 2], [3, 4], [5, 7]]
d
[[3, 2], [9, 2], [10, 12]]
"""


array([[ 3,  2],
       [ 9,  2],
       [10, 12]])

Write a function scalar_mult(s, m) that multiplies a matrix, m, by a scalar, s.

In [494]:
#1st
def scalar_mult(s, m):
  mult_matrix = s * m
  return mult_matrix
a = np.array([[1, 2], [3, 4]])
result = scalar_mult(3, a)
result

#2nd
def scalar_mult2(s, m):
  mult_matrix2 = s * m
  return mult_matrix2
b = np.array([[3, 5, 7], [1, 1, 1], [0, 2, 0], [2, 2, 3]])
result2 = scalar_mult(10, b)
#result2
#b
"""
a = [[1, 2], [3, 4]]
scalar_mult(3, a)
[[3, 6], [9, 12]]
b = [[3, 5, 7], [1, 1, 1], [0, 2, 0], [2, 2, 3]]
scalar_mult(10, b)
[[30, 50, 70], [10, 10, 10], [0, 20, 0], [20, 20, 30]]
b
[[3, 5, 7], [1, 1, 1], [0, 2, 0], [2, 2, 3]]
"""



array([[ 3,  6],
       [ 9, 12]])

Write functions row_times_column and matrix_mult:

In [485]:
#row = 0 column = 0
def row_times_column(m1, row, m2, column):
  row_time_column = np.dot(row,column)
  return row_time_column
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])
column = m2[:,0]
row = m1[0,:]
#print(len(m1),"x",len(m1[0])) # reading the dimension of a matrix
result = row_times_column(m1,row,m2,column)
print(result)

#row = 0 column = 1
def row_times_column(m1, row, m2, column):
  row_time_column = np.dot(row,column)
  return row_time_column
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])
column = m2[:,1]
row = m1[0,:]
#print(len(m1),"x",len(m1[0])) # reading the dimension of a matrix
result1 = row_times_column(m1,row,m2,column)
print(result1)

#row = 1 column = 0
def row_times_column(m1, row, m2, column):
  row_time_column = np.dot(row,column)
  return row_time_column
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])
column = m2[:,0]
row = m1[1,:]
#print(len(m1),"x",len(m1[0])) # reading the dimension of a matrix
result2 = row_times_column(m1,row,m2,column)
print(result2)

#row = 1 column = 1
def row_times_column(m1, row, m2, column):
  row_time_column = np.dot(row,column)
  return row_time_column
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])
column = m2[:,1]
row = m1[1,:]
#print(len(m1),"x",len(m1[0])) # reading the dimension of a matrix
result3 = row_times_column(m1,row,m2,column)
print(result3)

19
22
43
50


In [487]:
#1st
def matrix_mult(m1,m2):
  m_mult = np.dot(m1,m2) # same dimensions i.e. (2x2) & (2x2)
  return m_mult

m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])
result = matrix_mult(m1,m2)
for r1 in result:
  print(r1)

#2nd
m3 = np.array([[1, 2, 3],[4, 5, 6]])
m4 = np.array([[7, 8], [9, 1], [2, 3]])
result2 = [[0,0],
          [0,0]] # result returns 2x2 matrix

for i in range(len(m3)): # rows of m3
    for j in range(len(m4[0])): # columns of m4
        for k in range(len(m4)): # rows of m4
            result2[i][j] += m3[i][k] * m4[k][j] 
for r2 in result2:
    print(r2)

#3rd
m5 = np.array([[7, 8], [9, 1], [2, 3]])
m6 = np.array([[1, 2, 3], [4, 5, 6]])

result3 = [[0,0,0],
           [0,0,0],
           [0,0,0]] # returns 3x3 matrix
for i in range(len(m5)): # rows of m5
    for j in range(len(m6[0])): # columns of m6
        for k in range(len(m6)): # rows of m6
            result3[i][j] += m5[i][k] * m6[k][j] 
for r3 in result3:
    print(r3)



[19 22]
[43 50]
[31, 19]
[85, 55]
[39, 54, 69]
[13, 23, 33]
[14, 19, 24]


Write a function transpose that takes a matrix as an argument and returns is transpose:

In [509]:
#1st
def transpose(m):
  result_T = m.T
  return result_T

m = np.array([[3, 4, 6]])
result = transpose(m)
print(result)
print(m)

#2nd
def transpose2(m):
  result_T1 = m.T
  return result_T1
m = np.array([[3, 4, 6],[1, 5, 9]])
result1 = transpose(m)
print(result1)


[[3]
 [4]
 [6]]
[[3 4 6]]
[[3 1]
 [4 5]
 [6 9]]
