## Linear Algebra Quiz #3

![title](./img/3_0.jpeg)

We strongly suggest working with numpy :)

In [1]:
#Do your imports here
import numpy as np


![title](./img/3_2.png)
![title](./img/3_3.png)
Create a program that can output

- What is the value of element c23​ of Matrix C where C=A x B ?
- What is the value of element c23​ of Matrix C where C=B x A ?

In [5]:

# C = A x B
A = np.array([[3, 1, 2],[-5, 4, 1],[0, 3, -8]])
'''
def inverse_matrix(A):
    inverse = np.linalg.inv(A)
    return inverse
'''
B = np.array([[0, 5, -1],[3, 2, -1],[10, 0.5, 4]])
C = [[0,0,0],
              [0,0,0],
              [0,0,0]] # result returns 3x3 matrix
C1 = [[0,0,0],
              [0,0,0],
              [0,0,0]]          

for i in range(len(A)): # rows of A
    for j in range(len(B[0])): # columns of B
        
        for k in range(len(B)): # rows of B
            
            C[i][j] += A[i][k] * B[k][j] 

print("(In C = A x B) Value of c23 is:",C[1][2]) # to read c23

for r in C:
   print(r)

# C = B x A
for i1 in range(len(B)): # rows of B
    for j1 in range(len(A[0])): # columns of A
        for k1 in range(len(A)): # rows of A
            C1[i1][j1] += B[i1][k1] * A[k1][j1] 
print("(In C = B x A) Value of c23 is:",C1[1][2]) # to read c23

for r2 in C1:
    print(r2)

# okay numpy is great but... how would you inverse a matrix by hand?
'''
def inverse_matrix(A):
    return ""
'''
print('\n')
def inverse_matrix(A):
    return np.linalg.inv(A)
print("Inverse of matrix A is:\n", inverse_matrix(A))

(In C = A x B) Value of c23 is: 5.0
[23.0, 18.0, 4.0]
[22.0, -16.5, 5.0]
[-71.0, 2.0, -35.0]
(In C = B x A) Value of c23 is: 16.0
[-25.0, 17.0, 13.0]
[-1.0, 8.0, 16.0]
[27.5, 24.0, -11.5]


Inverse of matrix A is:
 [[ 0.2        -0.08        0.04      ]
 [ 0.22857143  0.13714286  0.07428571]
 [ 0.08571429  0.05142857 -0.09714286]]


![title](./img/3_1.png)
Create a program that can output

- What is the value of the ijth element if i = 2 and j=3?
- What is the value of the ijth element if i = 3 and j=1?

In [6]:
# Just answer using code --> easy stuff!

A = np.array([[3,0.6,4,-3],[-1.3,4,0,8.6],[7,0,-8,0.006]])
B = np.array([[3,-5.76,45,0],[2,-2,1.3,9],[-9,0,0,0]])
C = np.array([[0,1009,-66.7849,90],[0,5,4,-0.07],[-7.7,0,0,0]])

D = [[0,0,0,0],
     [0,0,0,0],
     [0,0,0,0]] # Dimensions 3x4

D = A + B - C
print(D)
print("Value of d23 is:",D[1][2]) # to read D[2][3]

print("Value of d31 is:",D[2][0]) # to read D[3][1]

# Harder
# Can you build a matrix solver that can do output the result given n matrices and a sequence of operations such as [add subtract multiply transpose?]
#Some ideas on valid operations: Multiplication Addition Subtraction Inverstion Transposed. 





[[ 6.000000e+00 -1.014160e+03  1.157849e+02 -9.300000e+01]
 [ 7.000000e-01 -3.000000e+00 -2.700000e+00  1.767000e+01]
 [ 5.700000e+00  0.000000e+00 -8.000000e+00  6.000000e-03]]
Value of d23 is: -2.7
Value of d31 is: 5.7


In [ ]:
# Harder
# Can you build a matrix solver that can do output the result given n matrices and a sequence of operations such as [add subtract multiply transpose?]
#Some ideas on valid operations: Multiplication Addition Subtraction Inverstion Transposed. 



![title](./img/3_3.png)
Create a program that can output
- How many rows will C have?
- How many columns will C have?
- What will be the value of c13​?

In [7]:
A = np.array([[0.6, -15, 2, 5, 98]])

B = np.array([[2,2,-4],[9,-14,0],[13,-0.5,44],[1,9,4],[0,0,5]])

C = [[0,0,0]]


for i in range(len(A)): # rows of A
    
    for j in range(len(B[0])): # columns of B
        
        for k in range(len(B)): # rows of B
            
            C[i][j] += A[i][k] * B[k][j] 


print(C) # to read c23
print(len(C)) # read rows
print(len(C[0])) # read column
print(C[0][2]) # read c13

[[-102.80000000000001, 255.2, 595.6]]
1
3
595.6
