In [1]:
import torch
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
# create a neural network class inheriting from the nn.Module
# Call it NeuralNetwork and make, and use "pass" in the constructor
# so that it doesn't give an error
# Instantiate one instance of it in variable net

net = 0

class NeuralNetwork(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim):
        super(NeuralNetwork, self).__init__()
        self.linear1 = nn.Linear(input_dim, hidden_dim)
        self.activation = nn.Sigmoid()
        self.linear2 = nn.Linear(hidden_dim, output_dim)
        
        
    def forward(self, x):
        layer1 = self.linear1(x)
        layer1_output = self.activation(layer1)
        layer2 = self.linear2(layer1_output)
        layer2_output = self.activation(layer2)
        
        return layer2_output
    
net = NeuralNetwork(10,5,1)

In [4]:
## get model
net

NeuralNetwork(
  (linear1): Linear(in_features=10, out_features=5, bias=True)
  (activation): Sigmoid()
  (linear2): Linear(in_features=5, out_features=1, bias=True)
)

In [5]:
## check the weights 
list(net.parameters())

[Parameter containing:
 tensor([[ 0.2587,  0.2740, -0.0734, -0.0729, -0.0730, -0.1021,  0.2262,  0.2939,
           0.2815, -0.1206],
         [ 0.2188, -0.0104, -0.1066,  0.1146, -0.0283, -0.3108,  0.1707, -0.1249,
           0.2108,  0.2360],
         [ 0.2846, -0.2920,  0.2381,  0.2420, -0.0855,  0.1476, -0.0183, -0.0709,
          -0.0758, -0.2736],
         [-0.0085, -0.1384,  0.0322,  0.2843,  0.1669, -0.0934,  0.0736, -0.0115,
           0.0068,  0.2048],
         [ 0.0345,  0.0314, -0.1117,  0.2373,  0.1249, -0.1180, -0.0164, -0.2661,
           0.2221, -0.2056]], requires_grad=True),
 Parameter containing:
 tensor([-0.3111,  0.2302, -0.1079,  0.1451,  0.0702], requires_grad=True),
 Parameter containing:
 tensor([[-0.0347, -0.0787,  0.0521,  0.1156, -0.1472]], requires_grad=True),
 Parameter containing:
 tensor([-0.3380], requires_grad=True)]

In [ ]:
## check individual weights
# list(net.linear1.parameters())

In [8]:
assert isinstance(net, NeuralNetwork)

In [12]:
# Rewrite the NeuralNetwork class so that the constructor receives
# as input the input_dim and num_hidden, respectively the dimension of 
# the input and the number of hidden neurons
# use pass again

class NeuralNetwork(nn.Module):
    pass
    def __init__(self, input_dim, num_hidden):
        super().__init__()
        pass


In [13]:
assert NeuralNetwork(input_dim=10, num_hidden=16)

In [6]:
# Rewrite the NeuralNetwork class so that the constructor receives
# as input the input_dim, num_hidden1 and num_hidden2, respectively the dimension of 
# the input and the number of hidden neurons for the first fully connected
# layer and the second. Define the attributes in the constructor
# that consists of the layers, call them fc1, fc2 and fc3 and a sigmoid.
# use pass again. Be careful to put the dimensions in the right places!
# Since we will do a binary classification problem, fc3 will have 1 neuron
# as output

class NeuralNetwork(nn.Module):
    def __init__(self, input_dim, num_hidden1, num_hidden2):
        super().__init__()
        self.fc1 = nn.Linear(input_dim, num_hidden1)
        self.fc2 = nn.Linear(num_hidden1, num_hidden2)
        self.fc3 = nn.Linear(num_hidden2, 1)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self, x):
        linear1 = self.fc1(x)
        activation1 = self.sigmoid(linear1)
        linear2 = self.fc2(activation1)
        activation2 = self.sigmoid(linear2)
        linear3 = self.fc3(activation2)
        output = self.sigmoid(linear3)
        return output
        
        

In [46]:
net = NeuralNetwork(2, 16, 16)


In [47]:
net

NeuralNetwork(
  (fc1): Linear(in_features=2, out_features=16, bias=True)
  (fc2): Linear(in_features=16, out_features=16, bias=True)
  (fc3): Linear(in_features=16, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)

In [48]:
# For training a model, use the following optimizer and loss

optimizer = torch.optim.Adam(net.parameters(), lr=0.01)
loss = nn.BCELoss()


In [49]:
data = pd.read_csv("data.csv", header =None)


In [50]:
data.head()

0         1  2
0  0.78051 -0.063669  1
1  0.28774  0.291390  1
2  0.40714  0.178780  1
3  0.29230  0.421700  1
4  0.50922  0.352560  1

In [51]:
# need to have data in array 

x = data.iloc[:,:2].values
y = data.iloc[:,-1].values

In [52]:
# convert to tensors
x_tensor = torch.tensor(x).float()
y_tensor = torch.tensor(y).float()


In [53]:
y_tensor_s = y_tensor.view(-1,1)
y_tensor_s.shape

torch.Size([100, 1])

In [54]:
y_pred_tensor = net(x_tensor)
loss_value = loss(y_pred_tensor, y_tensor_s)
print(f"Initial loss: {loss_value.item():.2f}")

Initial loss: 0.70


In [61]:
def model_fit(model, loss, optimizer, x,y, num_epochs):
    
    for epoch in range(num_epochs):
        optimizer.zero_grad()
        
        y_pred = model(x)
        
        loss_value = loss(y_pred,y)
        
        loss_value.backward()
        
        optimizer.step()
        print(f"loss: {loss_value.item():.2f}")
        
    return model
    
model_fit(net, loss, optimizer, x_tensor, y_tensor_s, 50)

    
    

loss: 0.14
loss: 0.14
loss: 0.14
loss: 0.14
loss: 0.14
loss: 0.14
loss: 0.14
loss: 0.14
loss: 0.14
loss: 0.14
loss: 0.14
loss: 0.14
loss: 0.14
loss: 0.14
loss: 0.14
loss: 0.14
loss: 0.14
loss: 0.14
loss: 0.14
loss: 0.14
loss: 0.14
loss: 0.14
loss: 0.14
loss: 0.14
loss: 0.14
loss: 0.14
loss: 0.14
loss: 0.14
loss: 0.14
loss: 0.14
loss: 0.14
loss: 0.14
loss: 0.14
loss: 0.14
loss: 0.14
loss: 0.14
loss: 0.14
loss: 0.14
loss: 0.14
loss: 0.14
loss: 0.14
loss: 0.14
loss: 0.14
loss: 0.14
loss: 0.14
loss: 0.14
loss: 0.14
loss: 0.14
loss: 0.14
loss: 0.14


NeuralNetwork(
  (fc1): Linear(in_features=2, out_features=16, bias=True)
  (fc2): Linear(in_features=16, out_features=16, bias=True)
  (fc3): Linear(in_features=16, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)