# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [5]:
print(np.__version__)
print(np.show_config())

1.20.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/shahi/anaconda3/envs/strive\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/shahi/anaconda3/envs/strive\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/shahi/anaconda3/envs/strive\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/shahi/anaconda3/envs/strive\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/shahi/anaconda3/envs/strive\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/shahi/anaconda3/envs/strive\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/shahi/anaconda3/envs/strive\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Use

#### 3. Create a null vector of size 10 (★☆☆)

In [6]:
z= np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆)

In [35]:
array = np.array([1,2,3])
#z = array.dtype
print((array.size * array.itemsize)) # one array element

12


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [37]:
!python -c "import numpy; numpy.info(numpy.add)"

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [40]:
array = np.zeros(10)

new_array [4] = 1
print(new_array)

[0. 0. 0. 0. 1. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [43]:
z = np.arange(10,50)
print (z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [51]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)


[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [54]:
Z = np.arange(9)
print(Z)
matrix = Z.reshape(3,3)
print(matrix)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [83]:
dete = np.nonzero([1,2,0,0,4,0])
print(dete)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [79]:
rest = np.zeros(9)
rest[0] = 1 
rest [4] = 1
rest[8] = 1
reshape = rest.reshape(3,3)
print(reshape)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [59]:
random = np.random.uniform(size=(3,3))
print (random)

[[0.9001118  0.34268582 0.2455802 ]
 [0.91963153 0.73131604 0.71028162]
 [0.95807004 0.88781338 0.35122363]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [96]:
arr = np.random.uniform(size=(10,10))
#print(arr)
min1 = arr.min()
max1 = arr.max()
print(min1, max1)

0.0010078234997386026 0.9997699854141924


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [111]:
Z = np.random.normal(size=(30))
Y = Z.mean()
#print(Z)
print(Y)



-0.14115645524123732


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [124]:
Z = np.ones([9])
#print(Z)
Z[4] = 0
rearrange = Z.reshape(3,3)

print(rearrange)


[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [125]:
Z = np.zeros([9])
#print(Z)
Z[4] = 1
rearrange = Z.reshape(3,3)

print(rearrange)

[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [13]:
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == (3 * 0.1))



nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [40]:
Z = np.zeros((5,5))
#print(Z)
Z[(1,0)] = 1
Z[(2,1)] = 2
Z[(3,2)] = 3
Z[(4,3)] = 4
#Z[11] = 2
#Z[17] = 3
#Z[23] = 4
#Y = Z.reshape(5,5)

print(Z)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [48]:
Z = np.zeros((8,8))
Z[::2,1::2] = 1
Z[1::2,::2] = 1

print(Z)


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [51]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [53]:
Z = np.tile(np.array([[1,0],[0,1]]), (4,4))
print (Z)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [74]:
Z = np.random.random((5,5))
X = np.mean(Z)
Dev = np.std(Z)
Y = ((Z - X)/Y)
print(Y)

[[-1.91738651 -0.4882538   0.30170938 -0.29756883  0.11561091]
 [-0.35802269 -0.2648673  -1.05492604 -0.12215645 -0.26847988]
 [-0.30462817 -0.62321594  0.09369994 -0.22696258 -0.01976388]
 [-0.17310946  0.83284567  0.31434377  3.30322561  0.13046746]
 [-2.26550289  0.52950714 -1.24805683 -0.34206358  0.42216353]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [76]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a",np.ubyte,  1)])

<ipython-input-76-afd3e171c99b>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [96]:
"""
Z = np.ones((5,3))
X = np.ones((3,2))
#Y = Z*X
Y = np.dot(Z,X)
print(Y)
"""
Z = np.dot(np.ones((5,3)),np.ones((3,2)))
print(Z)


[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [101]:
Z = np.arange(11)
Z[(3<Z) & (Z<=7)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [102]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [114]:
Z = 2
print("1.", Z**Z)
print("2.", 2 << Z >> 2)
print("3.", Z <- Z)
print("4.", 1j*Z)
print("5.", Z/1/1)
print("6.", Z<Z>Z)

1. 4
2. 2
3. False
4. 2j
5. 2.0
6. False


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [120]:
print("1.", (np.array(0) / np.array(0))) #1. 
print("2.", (np.array(0) // np.array(0))) #2. 
print("3.", (np.array([np.nan]).astype(int).astype(float))) #3. 

1. nan
2. 0
3. [-2.14748365e+09]


<ipython-input-120-cc3f73b42c39>:1: RuntimeWarning: invalid value encountered in true_divide
  print("1.", (np.array(0) / np.array(0)))
<ipython-input-120-cc3f73b42c39>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print("2.", (np.array(0) // np.array(0)))


#### 29. How to round away from zero a float array ? (★☆☆)

In [124]:
Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

[ -8.  -4.   7.  -1.  -4. -10.  -8.   6.   6.  -6.]


#### 30. How to find common values between two arrays? (★☆☆)

In [139]:
Y = np.random.randint(0,10,10)
print("Y",Y)
Z = np.random.randint(0,10,10)
print("Z", Z)
print("Intersection:", np.intersect1d(Y,Z))

Y [0 0 9 1 6 5 0 3 5 9]
Z [3 4 3 5 4 4 9 4 0 1]
Intersection: [0 1 3 5 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [141]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# to go on default settings back
_ = np.seterr(**defaults)


#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [144]:
print(np.sqrt(-1) == np.emath.sqrt(-1))
print (np.sqrt(-1))
print(np.emath.sqrt(-1))

False
nan
1j


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [154]:
Y = np.datetime64("today") - np.timedelta64(1)
T = np.Datetime64("today")
TO = np.Datetime64("today") + np.timedelta64(1)
print("Yesterday:", Y)
print("Today:", T)
print("Tomorrow:", TO)

Yesterday: 2021-09-23
Today: 2021-09-24
Tomorrow: 2021-09-25


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [165]:
Z = np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [195]:
A = np.ones(2)*2
B = np.ones(2)*9
Z = np.add(A, B,out=B)
X = np.divide(A,2,out=A)
neg = np.negative(X,out=X)
finalanswer = np.multiply(Z, neg, out=Z)
#print(Z)
#print(neg)
print("finalanswer", finalanswer)

finalanswer [-11.]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [196]:
A = np.random.uniform(0,10,10)

print( A - A%1)
print(A // 1)
print(np.floor(A))
print(A.astype(int))
print(np.trunc(A))

[3. 7. 9. 1. 3. 4. 6. 7. 5. 0.]
[3. 7. 9. 1. 3. 4. 6. 7. 5. 0.]
[3. 7. 9. 1. 3. 4. 6. 7. 5. 0.]
[3 7 9 1 3 4 6 7 5 0]
[3. 7. 9. 1. 3. 4. 6. 7. 5. 0.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [199]:
matrix = np.zeros([5,5])

matrix += np.arange(5)
print(matrix)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [203]:
def generator():
    for values in range(10):
        yield values
    
A = np.fromiter(generator(),dtype=float,count=-1)
print(A)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [216]:
A = np.linspace(0,1,11,endpoint=False)[1:]
print(A)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [226]:
A = np.random.random(10)
A.sort()
print(A)

[0.15185756 0.21443699 0.27011414 0.45515835 0.55241789 0.61262123
 0.658813   0.71508349 0.76971949 0.82587909]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [231]:
A = np.arange(15)
print(np.add.reduce(A))


105


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [257]:
A = np.random.randint(1,3,4)
B = np.random.randint(1,3,4)
print(A)
print(B)
C = np.allclose(A,B)
print(C)

D = np.array_equal(A,B)
print(D)

[2 1 1 2]
[2 1 1 2]
True
True


#### 43. Make an array immutable (read-only) (★★☆)

In [267]:
A = np.zeros(10)
A.flags.writeable = False # this makes the array read only and gives error when change is made
A[0] = 1
print(A)

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [282]:
A = np.random.random((10,2))
X = A[:,0] 
Y = A[:,1]
R = np.sqrt(X**2+Y**2)
theta = np.arctan(Y,X)

#print(X)
#print(Y)
print(R)
print(theta)


[0.71159091 0.44785237 0.80763865 0.90688419 0.66106043 0.45697753
 0.96244289 0.96648086 0.63167882 0.3007692 ]
[0.61589542 0.25625293 0.50220952 0.13068821 0.22838615 0.42796625
 0.4166666  0.32044093 0.49683532 0.02714767]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [285]:
A = np.random.random(10)
A[A.argmax()]=0
print(A)

[0.94483285 0.09602038 0.34522343 0.72121096 0.10736902 0.34367687
 0.47543954 0.8443384  0.         0.19835295]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [295]:
A = np.zeros((3,3), [("x",float),("y",float)])
A["x"], A["y"] = np.meshgrid(np.linspace(0,1,3), np.linspace(0,1,3))
print(A)



[[(0. , 0. ) (0.5, 0. ) (1. , 0. )]
 [(0. , 0.5) (0.5, 0.5) (1. , 0.5)]
 [(0. , 1. ) (0.5, 1. ) (1. , 1. )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [323]:
X = np.arange(3)
print(A)
Y = A + 2
print(Y)
C = 1.0 / np.subtract.outer(A, B)
print("final answer:", np.linalg.det(C))


[0 1 2]
[2 3 4]
final answer: -15.17037037037037


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [338]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    #print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
-1.7976931348623157e+308
1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

In [344]:
np.set_printoptions(threshold=float("inf"))
A = np.ones((4,4))
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [355]:
A = np.arange(10)
B = np.random.uniform(0,10)
sub = (np.abs(A-B)).argmin()
print(A[sub])

9


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [358]:
A = np.zeros(2, [("position", [("x", float, 1), ("y", float, 1)]), ("color", [("r", float, 1), ("g", float, 1), ("b", float, 1)])])
print(A)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-358-89908d25b66f>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  A = np.zeros(2, [("position", [("x", float, 1), ("y", float, 1)]), ("color", [("r", float, 1), ("g", float, 1), ("b", float, 1)])])


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [363]:
A = np.random.random((100,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
distance = np.sqrt((X-X.T)**2 + (Y-Y.T)**2)
print(distance)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [373]:
A = (np.random.rand(5)*5).astype(np.float32)
B = A.view(np.int32)
B[:] = A
print(B)

[2 2 4 2 4]


#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [375]:
A = np.arange(4).reshape(2,2)
for index, value in np.ndenumerate(A):
    print(index, value)
for index in np.ndindex(A.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3
(0, 0) 0.0
(0, 1) 1.0
(1, 0) 0.0
(1, 1) 1.0


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [385]:
X, Y = np.meshgrid(np.linspace(-1,1,4), np.linspace(-1,1,4))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-((D-mu)**2 / (2.0 * sigma**2)))
print(G)

[[0.36787944 0.57375342 0.57375342 0.36787944]
 [0.57375342 0.89483932 0.89483932 0.57375342]
 [0.57375342 0.89483932 0.89483932 0.57375342]
 [0.36787944 0.57375342 0.57375342 0.36787944]]


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [394]:
n = 5
p = 4
A = np.zeros((n,n))
np.put(A, np.random.choice(range(n*n), p, replace = False),1)
print(A)

[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 1.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [397]:
A = np.random.rand(4,4)

B = A - A.mean(axis=1).reshape(-1,1)

print(B)

[[ 0.11537468  0.17458589 -0.37929848  0.0893379 ]
 [-0.41297838 -0.05824489  0.43616184  0.03506143]
 [ 0.40774759 -0.18453647 -0.34683811  0.12362698]
 [-0.37932284  0.19990577 -0.01935753  0.19877461]]


#### 59. How to sort an array by the nth column? (★★☆)

In [411]:
A = np.random.randint(10,20,(4,4))
print(A)
print(A[A[:,1].argsort()])

[[12 13 15 16]
 [14 10 18 13]
 [12 19 17 19]
 [12 17 11 11]]
[[14 10 18 13]
 [12 13 15 16]
 [12 17 11 11]
 [12 19 17 19]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [472]:
A = np.random.randint(0,4,(4,4))
print(A)
print((~A.any(axis=0)).any())

[[1 1 3 1]
 [2 2 2 1]
 [1 0 0 1]
 [0 2 1 3]]
False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [489]:
A = np.random.uniform(0,1,5)
B = 0.5
n = A.flat[np.abs(A-B).argmin()]
print("A",A)
print(n) 

A [0.72267993 0.30049769 0.73096504 0.05841069 0.348758  ]
0.3487579959734801


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [501]:
array1 = np.arange(5).reshape(5,1)
array2 = np.arange(5).reshape(1,5)
iterator = np.nditer([array1,array2,None])
for A,B,C in iterator: C[...] = A + B
print(array1)
print(array2)
print(iterator.operands[2])

[[0]
 [1]
 [2]
 [3]
 [4]]
[[0 1 2 3 4]]
[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

In [12]:
array = np.arange(4).reshape(2,2)
print(array)
array[[0,1]] = array [[1,0]]
print(array)

[[0 1]
 [2 3]]
[[2 3]
 [0 1]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [23]:
def moving_average(A, n=3):
    result = np.cumsum(A, dtype=float)
    result[n:] = result [n:] -result[:-n]
    return result[n-1:] / n

B = np.array([1,2,3,4,5,6,7,8,9,10])

print(moving_average(B))

[2. 3. 4. 5. 6. 7. 8. 9.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)