## Remember that the solutions need to be saved int variable provided.

In [2]:
# Import the needed libraries
import numpy as np

**13. Create a 10x10 array with random values and find the minimum and maximum values**

In [3]:
# 1 point
sol1 = 0
# YOUR CODE HERE
arr = np.random.uniform(size=(10,10))
#print(arr)
min1 = arr.min()
max1 = arr.max()
print(min1, max1)

0.00756251725602386 0.9971990210543153


In [10]:
assert sol1.shape == (10,10)

AssertionError: 

**15. Create a 2d 10x10 array with 1 on the border and 0 inside**

In [9]:
#1 points
sol2 = 0

# YOUR CODE HERE
A = np.ones((10,10))
A[1:-1,1:-1] = 0
print(A)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
assert sol2.shape == (10,10)
assert sol2[0].all() == 1
assert sol2[:,0].all() == 1
assert sol2[1][1] == 0
assert sol2[2][2] == 0
assert sol2[3][3] == 0
assert sol2[4][4] == 0
assert sol2[1][2] == 0
assert sol2[2][3] == 0
assert sol2[3][4] == 0
assert sol2[4][5] == 0

**34. How to get all the dates corresponding to the month of July 2016**

In [4]:
#2 points
sol3 = 0

# YOUR CODE HERE
A = np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(A)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [ ]:
assert sol3.shape == (31,)
assert type(sol3[0]) is np.datetime64

**42. Consider two random arrays based on the normal and uniform distributions 10x10 sol41 and sol42, check if they are equal**

In [23]:
#2 points
sol41 = 0
sol42 = 0
comparisson = 0
A = np.random.normal(size=(10,10))
B = np.random.uniform(size=(10,10))
#print(A)
#print(B)
"""
C = np.allclose(A,B)
print(C)

D = np.array_equal(A,B)
print(D)
"""
print(A == B)

[[False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]]


In [ ]:
bol = True

for l in comparisson:
    for c in l:
        if c:
            bol = False


assert bol

**72. How to swap two rows of an array?** 

In [ ]:
#3 points
sol5 = np.array([[1,2,3],[4,5,6]])

# YOUR CODE HERE
raise NotImplementedError()

In [ ]:
assert sol5[0][0] == 4
assert sol5[0][1] == 5
assert sol5[0][2] == 6

assert sol5[1][0] == 1
assert sol5[1][1] == 2
assert sol5[1][2] == 3


**75. How to compute averages using a sliding window over an array?**

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
sol6 = 0
# YOUR CODE HERE
raise NotImplementedError()


In [ ]:
assert sol6[-1] == 5.5
assert sol6[0] == 0.1
assert sol6[4] == 1.5